[build]
  publish = "."
  functions = "serverless/netlify/functions"

# Optional: cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


