backend:
  name: git-gateway
  branch: main

publish_mode: simple

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "products"
    label: "Products"
    label_singular: "Product"
    description: "Edit products for the main page"
    files:
      - file: "assets/data/products.json"
        label: "Products"
        name: "products"
        editor:
          preview: true
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            summary: "{{fields.name}} — ${{fields.priceCents}}"
            fields:
              - { label: "ID", name: "id", widget: "number", required: true }
              - { label: "Name", name: "name", widget: "string", required: true }
              - { label: "Price (cents)", name: "priceCents", widget: "number", required: true }
              - { label: "Material", name: "material", widget: "string", required: true }
              - { label: "Limited Edition", name: "limited", widget: "boolean", default: false, required: false }
              - { label: "Remaining Stock", name: "remaining", widget: "number", default: 0, required: false }
              - { label: "Sold Out", name: "soldOut", widget: "boolean", default: false, required: false }
              - { label: "Image", name: "image", widget: "image", allow_multiple: false, required: false }